services:
  medialyze:
    image: ghcr.io/frederikemmer/medialyze:latest
    container_name: medialyze
    ports:
      - "${HOST_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_HOST_DIR:-./config}:/config
      - ${MEDIA_HOST_DIR:-./media}:/media:ro
      # additional media mounts, if needed. Extend this pattern if needed:
      # /PATH/TO/MEDIA1:/media/MEDIA1:ro
